#This workflow builds a docker image and pushes it to ECR, it calls another workflow.

name: Build and Push container image

on:  
  push:
    branches: [ $default-branch ]
  
  workflow_dispatch:


jobs:
  call-workflow-paasing-data:
    uses: 365scores/workflows/.github/workflows/BuildNPushContainer.yml@main
    with:
      ## The path of the docker file, relative to the repo main folder (required)
      dockerfile_path: "./"
      ## The name of the dockerfile, only needed to specify id the name is not "Dockerfile", casing matters. unmark to use
      # dockerfile_name: "OtherName"
      ## The working directory path for the docker build command. the default value is "." , that is the commun case. unmark to use
      # working_directory_path: "/path/path"
      ## The ECR repository name (required)
      ecr_repository: #reponame
    secrets: inherit
